### ISSUE TITLE
Raw descriptors are not handled safely

### ISSUE THREAD

**Issue by ustulation** [eminence/udt-rs#11]
[This](https://github.com/eminence/udt-rs/blob/efc8b1ae795c431924df5d87ac4de4ff7791253d/src/lib.rs#L80) and [this](https://github.com/eminence/udt-rs/blob/efc8b1ae795c431924df5d87ac4de4ff7791253d/src/lib.rs#L66) are not safe. The correct way should have been `into_raw...()` instead of `as_raw...()`. Otherwise the function is taking the ownership of the supplied socket but then does not cause an "into" from it. So at the end of the function the socket is going to be dropped leaving the obtained descriptor dangling. This might lead to Undefined Behaviour. So we should use the `into_...` set of functions really IMO.

**Comment by eminence** [comment]
Thanks, I'll take a look.

This code-base was written several years ago, and will benefit from a good review.  So thank you for bringing a set of fresh eyes to this code.

**Comment by ustulation** [comment]
Ah np, i'll keep the issues coming as i use/read it and think something is worthy of getting flagged. It's already a good crate binding to a C++ interface - quite useful :)
