### ISSUE TITLE
memory consumption

### ISSUE THREAD

**Issue by mcginty** [eminence/udt-rs#5]
I noticed that shoop was using a lot of CPU even in relatively low-bandwidth situations, so I ran it through valgrind and Instruments. I definitely do some excess allocations in shoop, but it looks like UDT has a lot of allocation and memory thrash. My first guess is just that recvmsg allocates a new `Vec` for every call instead of accepting a `&mut [u8]` argument.

Vangrind heap summary for a shoop transfer of a 5.7MB file.

```
==51911== HEAP SUMMARY:
==51911==     in use at exit: 34,307 bytes in 248 blocks
==51911==   total heap usage: 17,127 allocs, 16,879 frees, 5,647,010,936 bytes allocated
```

Instruments profiling info:
<img width="758" alt="screen shot 2016-08-08 at 3 43 59 pm" src="https://cloud.githubusercontent.com/assets/373823/17474239/28f56fa8-5d7f-11e6-8f26-5fba681ae9fa.png">

Again, the valgrind info especially is probably not that useful because I think I'm doing a lot of excess allocation in shoop too, but hopefully the profiler info is useful.

**Comment by mcginty** [comment]
Sorry, that profile screenie was with the system allocator. I did it again with rust's jemalloc, it seems to lead to a more clear profile in this case at least.

<img width="836" alt="screen shot 2016-08-08 at 3 51 49 pm" src="https://cloud.githubusercontent.com/assets/373823/17474450/22191b5c-5d80-11e6-87a3-5e820c33dac7.png">

**Comment by eminence** [comment]
Have you updated to udt-rs 0.2.0 yet?  I'm curious if things are any different now that we're using the new recv API you suggested

**Comment by mcginty** [comment]
Yeah I have - this bug report was pre-0.2. I haven't run much extensive memory analysis on shoop after 0.2 but I know it's much lower. I think the biggest problem is now sodiumoxide doing the same thing, where it's allocating new Vec<u8>s with every open/seal operation. I'm going to close this.
